### ISSUE TITLE
No module named 'fcntl'

### ISSUE THREAD

**Issue by sryu1** [optuna/optuna-dashboard#424]
### Description

I get the error below, it seems like gunicorn only works for Unix based OS... I'm on Windows 11.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Scripts\optuna-dashboard.exe\__main__.py", line 7, in <module>
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna_dashboard\_cli.py", line 130, in main
    run_gunicorn(app, args.host, args.port, args.quiet)
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna_dashboard\_cli.py", line 45, in run_gunicorn
    from gunicorn.app.base import BaseApplication
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

### How to Reproduce

run `optuna-dashboard sqlite:///db.sqlite3`

### Python version

3.11.2

### Optuna version

3.1.0

### optuna-dashboard version or git revision

0.9.0

### Web browser

Google Chrome

**Comment by sryu1** [comment]
yes, that works, thank you!
