### ISSUE TITLE
Error creating dashboard sqlite3 database

### ISSUE THREAD

**Issue by DiasBakh** [optuna/optuna-dashboard#812]
### Description

Guys!!! You are doing amazing things!!!

- Installed latest version
- Run optuna dashboard:

```python
optuna-dashboard sqlite:///optuna_db.sqlite3
```

Got error:

```shell
Traceback (most recent call last):
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: version_info

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 73, in _create_scoped_session
    yield session
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 1043, in _init_version_info_model
    version_info = models.VersionInfoModel.find(session)
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna/storages/_rdb/models.py", line 578, in find
    version_info = session.query(cls).one_or_none()
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2753, in one_or_none
    return self._iter().one_or_none()  # type: ignore
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2826, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: version_info
[SQL: SELECT version_info.version_info_id AS version_info_version_info_id, version_info.schema_version AS version_info_schema_version, version_info.library_version AS version_info_library_version 
FROM version_info]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/bin/optuna-dashboard", line 8, in <module>
    sys.exit(main())
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna_dashboard/_cli.py", line 119, in main
    storage = get_storage(args.storage, storage_class=args.storage_class)
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna_dashboard/_storage_url.py", line 58, in get_storage
    return guess_storage_from_url(storage)
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna_dashboard/_storage_url.py", line 69, in guess_storage_from_url
    return get_rdb_storage(storage_url)
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna_dashboard/_storage_url.py", line 76, in get_rdb_storage
    return RDBStorage(storage_url, skip_compatibility_check=True, skip_table_creation=True)
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 232, in __init__
    self._version_manager = _VersionManager(self.url, self.engine, self.scoped_session)
  File "/home/lgblkb/.cache/pypoetry/virtualenvs/salesinventory-ml-iSO67ysL-py3.10/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 1038, in __init__
    self._init_version_info_model()

```

- Checked created sqlite3 file. It is empty.
- Using `poetry` for dependency management.

```toml
[tool.poetry.dependencies]
python = "^3.10,<3.13"
# ... lots of other packages
optuna = "^3.5.0"
optuna-dashboard = "^0.14.0"
```

### How to Reproduce

1. Optuna's objective function is '...'.
2. Run optuna-dashboard with '...'
3. Open '...' page, then click '...'.
4. An error occurs.

### Python version

Python 3.10.12

### Optuna version

3.5.0

### optuna-dashboard version or git revision

0.14.0

### Web browser

Google Chrome, Firefox, etc.

**Comment by c-bata** [comment]
According to the error messages, there are no tables for Optuna in `optuna_db.sqlite3`. So I don't think this is a bug.  For further queries, please post your question in the https://github.com/optuna/optuna/discussions.
